apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-v1
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: app-v1
    spec:
      containers:
      - image: app:v1
        name: app-v1
        ports:
        - containerPort: 8080
        env:
        -
          name: BACKEND_URL
          value: http://localhost:8081/
      - image: backend:v1
        name: rolling-backend
