version: '3'
services:
  app:
    image: app:v2
    ports:
     - "8080:8080"
    environment:
      BACKEND_URL: http://backend:8081/
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
  backend:
    image: backend:v2
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
